In [35]:
import torch
from torch import Tensor

from alphazero import PolicyValueNet

In [36]:
model: PolicyValueNet = torch.load("./data/policy_value_net_20.pth").to("cpu")

In [37]:
import json

model.eval()

with open("./positions/start.json", encoding="utf-8") as f:
    start_pos: list = json.load(f)

with open("./positions/opening.json", encoding="utf-8") as f:
    opening_pos: list = json.load(f)

with open("./positions/middlegame.json", encoding="utf-8") as f:
    middlegame_pos: list = json.load(f)

with open("./positions/matein1.json", encoding="utf-8") as f:
    matein1_pos: list = json.load(f)

In [38]:
for pos in (start_pos, opening_pos, middlegame_pos, matein1_pos):
    p_hat: Tensor
    value: Tensor
    p_hat, value = model.forward(Tensor(pos).unsqueeze(0))

    p: Tensor = torch.exp(p_hat).flatten()
    print(torch.argmax(p))
    print(value.flatten())

  

tensor(80)
tensor([0.0018], grad_fn=<ViewBackward0>)
tensor(93)
tensor([-0.0029], grad_fn=<ViewBackward0>)
tensor(23)
tensor([0.0162], grad_fn=<ViewBackward0>)
tensor(68)
tensor([-0.0011], grad_fn=<ViewBackward0>)
